dataset:
  path: ../../input/ai-hackaton
  train: final_train.csv
  test: final_test.csv

weight:
  w1: 0.5
  w2: 0.5
  w3: 0
  w4: 0

submit:
  path: ../../submit
  name: cnn_cat_lightgbm_ensemble.csv
