dataset:
  path: ../../input/ai-hackaton

model:
  fold: 5
  verbose: 100

params:
  boosting_type: gbdt
  objective: multiclass
  n_estimators: 26000
  n_jobs: -1
  random_state: 42
  learning_rate: 0.007778313207178196
  max_depth: 3
  metric: multi_logloss
  min_child_samples: 106
  min_child_weight: 0.8041750109464992
  num_leaves: 22
  colsample_bytree: 0.16709557931179375
  reg_alpha: 0.28812516459050697
  reg_lambda: 0.547269122326666
  subsample: 0.9881982429404655

submit:
  path: ../../submit
  name: 5fold_lightgbm.csv
