dataset:
  path: ../../input/ai-hackaton

model:
  fold: 5
  verbose: 100

params:
  random_state: 42
  boosting_type: gbdt
  n_jobs: -1
  objective: multiclass
  metric: multi_logloss
  n_estimators: 10000
  colsample_bytree: 0.7631060030933504
  learning_rate: 0.22097704117952338
  max_depth: 17
  min_child_samples: 99
  min_child_weight: 0.8266762761991168
  num_leaves: 30
  reg_alpha: 0.9327260596737305
  reg_lambda: 0.8285798426419753
  subsample: 0.5826444493948311
submit:
  path: ../../submit
  name: lgbm_baseline.csv
