dataset:
  path: ../../input/ai-hackaton
  test: best_fea_test.pkl
  train: best_fea_train.pkl
model:
  fold: 5
  fold_name: group
  verbose: 100
params:
  boosting_type: gbdt
  colsample_bytree: 0.2788441133807552
  colsample_bytree_seed: 42
  learning_rate: 0.0367756027452049
  max_depth: 9
  min_child_samples: 885
  min_child_weight: 43.16734307889972
  min_split_gain: 0.10496990541124217
  n_estimators: 10000
  n_jobs: -1
  num_leaves: 1018
  objective: rmse
  reg_alpha: 8.219772826786357
  reg_lambda: 1.6709557931179373
  subsample: 0.8339152856093507
  subsample_freq: 81
  subsample_seed: 42
  drop_seed: 42
  verbosity: -1
